name: Build Influencer

on:
  push:
    branches: [main]

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - name: Code quality check
        uses: actions/checkout@v4

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 19.x
          #cache: "npm"
          #cache-dependency-path: package-lock.json
      #- run: npm ci

      #- name: Run Tests
      #run: npm run test:ci

      - name: Install Dependencies
        run: npm install --force

      - name: Build
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4

        with:
          name: influencer-build-artifact
          path: dist

  deploy-angular:
    runs-on: ubuntu-latest
    needs: build-angular

    steps:
      - name: Test
        run: echo "test step"
